/// App-wide string constants for Bengali & English
class AppStrings {
  AppStrings._();

  // ─── Bengali ────────────────────────────────────────
  static const Map<String, String> bn = {
    'appName': 'বিডিএআই',
    'tagline': 'বাংলাদেশের নিজস্ব AI সহকারী',
    'madeBy': 'বিডিএআই টেকনোলজি কর্তৃক নির্মিত',
    'version': 'সংস্করণ',
    'language': 'ভাষা',
    'darkMode': 'ডার্ক মোড',
    'voiceReply': 'ভয়েস রিপ্লাই',
    'settings': 'সেটিংস',
    'newChat': 'নতুন চ্যাট',
    'history': 'চ্যাট ইতিহাস',
    'noHistory': 'কোনো চ্যাট নেই',
    'logout': 'লগআউট',
    'loginTitle': 'বিডিএআই-তে স্বাগতম',
    'loginBtn': 'Google দিয়ে প্রবেশ করুন',
    'loginNote': 'Demo mode — প্রকৃত লগইন নেই',
    'inputHint': 'বাংলায় বা ইংরেজিতে লিখুন...',
    'listening': 'শুনছি... কথা বলুন',
    'speaking': 'বলছে...',
    'thinking': 'ভাবছি...',
    'imageRendering': 'ছবি তৈরি হচ্ছে...',
    'startConvo': 'বিডিএআই-কে কিছু জিজ্ঞেস করুন',
    'startConvoSub': 'চ্যাট করুন, ছবি তৈরি করুন, কোড লিখুন',
    'copyText': 'কপি',
    'copied': 'কপি হয়েছে',
    'upload': 'ছবি / ফাইল আপলোড',
    'imageGen': 'ছবি তৈরি করুন',
    'imageEdit': 'ছবি এডিট করুন',
    'faceSwap': 'ফেস সোয়াপ',
    'clearChat': 'চ্যাট মুছুন',
    'clearConfirm': 'চ্যাট মুছে ফেলবেন?',
    'clearMsg': 'সকল মেসেজ মুছে যাবে।',
    'yes': 'হ্যাঁ',
    'cancel': 'বাতিল',
    'errorConn': 'সংযোগ ব্যর্থ হয়েছে',
    'errorApi': 'API error হয়েছে',
    'imageReady': 'ছবি তৈরি হয়েছে:',
    'editReady': 'ছবি এডিট হয়েছে:',
    'swapReady': 'ফেস সোয়াপ হয়েছে:',
    'demoUser': 'Demo ব্যবহারকারী',
    'beta': 'বেটা',
    'appInfo': 'অ্যাপ তথ্য',
    'appearance': 'চেহারা',
    'voiceSettings': 'ভয়েস সেটিংস',
    'languageSetting': 'ভাষা নির্বাচন',
    'bengali': 'বাংলা',
    'english': 'English',
    'new_': 'নতুন',
  };

  // ─── English ─────────────────────────────────────────
  static const Map<String, String> en = {
    'appName': 'BDAi',
    'tagline': "Bangladesh's own AI assistant",
    'madeBy': 'Made by BDAi Technology',
    'version': 'Version',
    'language': 'Language',
    'darkMode': 'Dark Mode',
    'voiceReply': 'Voice Reply',
    'settings': 'Settings',
    'newChat': 'New Chat',
    'history': 'Chat History',
    'noHistory': 'No chats yet',
    'logout': 'Logout',
    'loginTitle': 'Welcome to BDAi',
    'loginBtn': 'Continue with Google',
    'loginNote': 'Demo mode — no real login',
    'inputHint': 'Type in Bengali or English...',
    'listening': 'Listening... speak now',
    'speaking': 'Speaking...',
    'thinking': 'Thinking...',
    'imageRendering': 'Generating image...',
    'startConvo': 'Ask BDAi anything',
    'startConvoSub': 'Chat, generate images, write code',
    'copyText': 'Copy',
    'copied': 'Copied!',
    'upload': 'Upload image / file',
    'imageGen': 'Generate Image',
    'imageEdit': 'Edit Image',
    'faceSwap': 'Face Swap',
    'clearChat': 'Clear Chat',
    'clearConfirm': 'Clear all messages?',
    'clearMsg': 'This cannot be undone.',
    'yes': 'Yes',
    'cancel': 'Cancel',
    'errorConn': 'Connection failed',
    'errorApi': 'API error occurred',
    'imageReady': 'Image generated:',
    'editReady': 'Image edited:',
    'swapReady': 'Face swap done:',
    'demoUser': 'Demo User',
    'beta': 'Beta',
    'appInfo': 'App Info',
    'appearance': 'Appearance',
    'voiceSettings': 'Voice Settings',
    'languageSetting': 'Language',
    'bengali': 'বাংলা',
    'english': 'English',
    'new_': 'New',
  };
}
